pipelines:
  workshop-config-service:
    group: workshop
    label_template: "${COUNT}"
    locking: off
    # setting materials
    materials:
      app:
        git: https://github.com/wuhan-learning/mst-config-server.git
        branch: master
    # setting stages
    stages:
      - build:
          clean_workspace: yes
          jobs:
            build:
              environment_variables:
                DOCKER_REGISRTY: 127.0.0.1
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-e"
                      - "./scripts/build.sh"
                    run_if: passed
      - deploy:
          clean_workspace: yes
          jobs:
            deploy:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-e"
                      - "./scripts/deploy.sh"
                    run_if: passed
